### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by smilesikand** [Zeg-AI/Zeg-AI.github.io#2]
1. Contact form is not integrated to Google Spreadsheet OR email
2. Map (below) is not working

**Comment by himanshu0128** [comment]
can you elaborate first point?

**Comment by smilesikand** [comment]
Yes. Say, I am a visitor and leave my contact details on the form and click 'submit'. It doesn't go anywhere. We can integrate it with Google-sheet so that the details are saved for us.

**Comment by himanshu0128** [comment]
#7

**Comment by smilesikand** [comment]
2. Map is now fixed but footer has got distorted on contact us page @decentname

**Comment by himanshu0128** [comment]
#11
