### ISSUE TITLE
Blog integration

### ISSUE THREAD

**Issue by smilesikand** [Zeg-AI/Zeg-AI.github.io#3]
1. Medium blog needs to be integrated to http://zeg.ai/blog/. Check if this is paid, we'll do something else..

**Comment by smilesikand** [comment]
@decentname here's the blog which can be inegrated: https://medium.com/zeg-ai

**Comment by himanshu0128** [comment]
Medium gave the feature earlier but now we can use its api. Some of the blogs made previously:
https://blog.faisalkhan.com/
https://blog.reynard.com.br/

**Comment by smilesikand** [comment]
Great. It works, if it's not paid.

**Comment by himanshu0128** [comment]
Done
